\LoadClass{article}

\RequirePackage{fancyhdr}
\RequirePackage{amsmath}
\RequirePackage{amsfonts}
\RequirePackage{amsthm}
\RequirePackage{amssymb}
\RequirePackage{frame}

\RequirePackage{paralist}
\RequirePackage{xcolor}


\newcommand{\TODO}{{\color{red} TODO}}


\pagestyle{fancy}
\fancyhead[L]{Jingyi Long}
\fancyhead[R]{Algebraic Curves}

\def\gt{>}
\def\lt{<}

\newtheorem{problem}{Problem}
\newtheorem{theorem}{Theorem}
\newtheorem{proposition}{Proposition}
\newtheorem{corollary}{Corollary}
\newtheorem{lemma}{Lemma}
\newtheorem{remark}{Remark}


\newenvironment{solution}
    {\textit{Solution:}}
    {}